import React from 'react'

export default function AboutPage() {
    return (
        <div>
            <p>Thie app was built using the OpenAI API. That is, the band names are being generated by artificial intelligence models. Selecting a genre and clicking the generate button submits a form to a server, which then makes an API call with a specific prompt</p>
        </div>
    )
}
